In [2]:
import pandas as pd
from gp import GPTreebank
import operators as ops
import math

In [3]:
op = [ops.PROD]
gp = GPTreebank(operators = op)
df = pd.DataFrame({'x': [0., 2., 4., 6., 8.,]})
t = [
    gp.tree("([float]<PROD>([float]x)([int]1))", x=df['x']),
    gp.tree("([float]<PROD>([float]x)([int]3))", x=df['x']),
    gp.tree("([float]<PROD>([float]x)([int]5))", x=df['x']),
    gp.tree("([float]<PROD>([float]x)([int]7))", x=df['x']),
    gp.tree("([float]<PROD>([float]x)([int]9))", x=df['x']),
    gp.tree("([float]<PROD>([float]6.)([int]6))")
]
t0 = pd.Series([0., 0., 0., 0., 0.])
t1 = pd.Series([0., 10., 20., 30., 40.])
res1, bes1 = gp.get_err_scores(t1, best_tree=True, rmses=True, best_rmse=True)
#

In [4]:
pop = pd.DataFrame({'trees': gp.get_all_root_nodes()[float]})
results = pd.DataFrame({'estimates': [None]*pop.shape[0]})
for i, t in enumerate(pop['trees']):
    results['estimates'][i] = t()
results['estimates'][5]

0    36.0
dtype: float64

In [ ]:
res1, bes1 = gp.get_err_scores(t1, best_tree=True, rmses=True, best_rmse=True)

In [ ]:
res1['mses']

0      24.0
1     216.0
2     600.0
3    1176.0
4    1944.0
5    1296.0
Name: mses, dtype: float64

In [ ]:
bes1

{'best_mse': 0.0,
 'best_tree': '[tree("([float]<PROD>([float]x)([int]5))")]',
 'best_rmse': 0.0}

In [ ]:
pop

trees  \
0  [([0.0, 2.0, 4.0, 6.0, 8.0]), (1)]   
1  [([0.0, 2.0, 4.0, 6.0, 8.0]), (3)]   
2  [([0.0, 2.0, 4.0, 6.0, 8.0]), (5)]   
3  [([0.0, 2.0, 4.0, 6.0, 8.0]), (7)]   
4  [([0.0, 2.0, 4.0, 6.0, 8.0]), (9)]   
5                        [(6.0), (6)]   

                                             results  
0  0    0.0
1    2.0
2    4.0
3    6.0
4    8.0
d...  
1  0     0.0
1     6.0
2    12.0
3    18.0
4    2...  
2  0     0.0
1    10.0
2    20.0
3    30.0
4    4...  
3  0     0.0
1    14.0
2    28.0
3    42.0
4    5...  
4  0     0.0
1    18.0
2    36.0
3    54.0
4    7...  
5                           0    36.0
dtype: float64

In [ ]:
pop['results'][3]

0     0.0
1    14.0
2    28.0
3    42.0
4    56.0
dtype: float64

In [ ]:
pop.shape

(6, 2)

In [ ]:
df_t = pd.Series([0.,2.,4.,6., 8.])

In [ ]:
b=9

In [ ]:
df_t*b

0     0.0
1    18.0
2    36.0
3    54.0
4    72.0
dtype: float64

In [ ]:
(df_t*b)**2

0       0.0
1     324.0
2    1296.0
3    2916.0
4    5184.0
dtype: float64

In [ ]:
((df_t*b)**2).sum()

9720.0

In [ ]:
((df_t*b)**2).mean()

1944.0

In [ ]:
mses = pd.Series([24.,216.,600.,1176.,1944.,1296.])

In [ ]:
(mses**-1).round(6)

0    0.041667
1    0.004630
2    0.001667
3    0.000850
4    0.000514
5    0.000772
dtype: float64

In [ ]:
res1['imses']

0    0.041667
1    0.004630
2    0.001667
3    0.000850
4    0.000514
5    0.000772
Name: imses, dtype: float64

In [ ]:
(mses**.5).round(4)

0     4.8990
1    14.6969
2    24.4949
3    34.2929
4    44.0908
5    36.0000
dtype: float64

In [ ]:
import math
import numpy as np

def softmax(errors):
    summed_exp_err = np.exp(errors).sum()[0].item()
    return errors.apply(lambda z: np.exp(z)/summed_exp_err)
    

In [ ]:
err = pd.DataFrame({'err': [1., 2., 3., 4.]})

In [ ]:
np.exp(err).sum()

err    84.791025
dtype: float64

In [ ]:
err = pd.DataFrame({'err': [1., 2., 3., 4., float('inf')]})
sm = softmax(err)
print(sm)
print(sm.sum())

inf
   err
0  1.0
1  2.0
2  3.0
3  4.0
4  inf
   err
0  0.0
1  0.0
2  0.0
3  0.0
4  NaN
err    0.0
dtype: float64


In [ ]:
import random
import math

In [ ]:
def diffs(n = 1000000):
    totals = np.array([0] * 5)
    w = np.array([.5, .3, .1, .07, .03])
    target = w * n
    print(target)
    for _ in range(n):
        totals[random.choices([0,1,2,3,4], weights = w)[0]] += 1
    return (totals-target)/totals

d = np.abs(diffs(200000))
print(d)
d < 0.05

[100000.  60000.  20000.  14000.   6000.]
[0.00067045 0.00071615 0.00049975 0.00948068 0.02040816]


array([ True,  True,  True,  True,  True])

In [ ]:
max([math.fabs(sum(random.choices([0,1], k=10000))-5000) for _ in range(1000)])

172.0

In [ ]:
math.fabs(45)

45.0

In [9]:
import random

for x in range(10):
    print(random.choices(['a', 'b', 'c'], k=2))

['c', 'a']
['b', 'c']
['c', 'a']
['b', 'c']
['b', 'b']
['c', 'a']
['c', 'c']
['b', 'b']
['c', 'b']
['c', 'a']


In [13]:
sum([math.fabs((sum([not random.randrange(4) for i in range(20000)])-5000) < 200) for j in range(20)])

20.0

In [12]:
import math